# Supabase credentials
SUPABASE_URL = "https://jiwjcittpzjsgnmecuaz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppd2pjaXR0cHpqc2dubWVjdWF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5ODYxMjksImV4cCI6MjA3OTU2MjEyOX0.d7MLjBBzFHNmGyS3VRqoo1EjoZ6xtzabUenOGYR2YoE"